import { useState, useEffect } from 'react';
import api from '../services/api';
import Markdown from './report/Markdown';
import FindingsList from './report/FindingsList';
import LoadingState from './common/LoadingState';
import ErrorAlert from './common/ErrorAlert';

export default function ReportDisplay({ taskId, onReset }) {
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [progress, setProgress] = useState('Initializing...');

  useEffect(() => {
    if (!taskId) return;
    
    const fetchResults = async () => {
      try {
        setLoading(true);
        setError(null);
        
        const data = await api.getResults(taskId, {
          onProgress: setProgress
        });
        
        setResults(data);
        setLoading(false);
      } catch (err) {
        console.error('Error fetching results:', err);
        setError(err.message || 'Failed to fetch results');
        setLoading(false);
      }
    };

    fetchResults();
  }, [taskId]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 p-4">
        <div className="max-w-6xl mx-auto space-y-8">
          <LoadingState title="Research in Progress" subtitle={progress} />
          <div className="space-y-6">
            <div className="loading-pulse modern-card h-64"></div>
            <div className="loading-pulse modern-card h-48"></div>
            <div className="loading-pulse modern-card h-56"></div>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 p-4">
        <div className="max-w-4xl mx-auto">
          <div className="error-card text-center">
            <div className="text-red-500 text-6xl mb-4">⚠️</div>
            <h2 className="text-2xl font-bold text-red-900 mb-4">Research Failed</h2>
            <ErrorAlert message={error} className="mb-6" />
            <button 
              onClick={onReset}
              className="btn-primary bg-gradient-to-r from-red-500 to-red-600"
            >
              Start New Research
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 p-4">
      <div className="max-w-6xl mx-auto space-y-8">
        {/* Header */}
        <div className="modern-card">
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <div className="w-10 h-10 bg-gradient-to-r from-green-500 to-emerald-500 rounded-xl flex items-center justify-center shadow-lg">
                  <span className="text-white text-lg">📊</span>
                </div>
                <h1 className="text-3xl font-bold text-gray-900">Research Report</h1>
              </div>
              <p className="text-gray-600 text-lg">Comprehensive analysis completed</p>
            </div>
            <button 
              onClick={onReset}
              className="btn-secondary"
            >
              🔄 New Research
            </button>
          </div>
        </div>

        {/* Original Query */}
        <div className="modern-card">
          <h2 className="text-xl font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <span className="text-blue-500">❓</span>
            Original Research Question
          </h2>
          <div className="bg-blue-50/80 backdrop-blur-sm rounded-xl p-6 border border-blue-200/50">
            <p className="text-gray-800 text-lg italic leading-relaxed">
              "{results?.original_query || 'No query provided'}"
            </p>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="report-summary-card">
          <h2 className="text-xl font-semibold text-gray-900 mb-6 flex items-center gap-2">
            <span className="text-purple-500">📋</span>
            Executive Summary
          </h2>
          <div className="prose-modern">
            <Markdown>{results?.summary || results?.final_report || 'Summary not available'}</Markdown>
          </div>
        </div>

        {/* Detailed Findings */}
        <div className="modern-card">
          <h2 className="text-xl font-semibold text-gray-900 mb-6 flex items-center gap-2">
            <span className="text-emerald-500">🔍</span>
            Detailed Findings
          </h2>
          <FindingsList findings={results?.findings || []} />
        </div>

        {/* Footer */}
        <div className="modern-card text-center">
          <p className="text-gray-500 text-sm">
            Report generated by Deep Research AI Agent • {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
}
